### PR TITLE
Set URLs of JCON to final

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Review by xuanxu — APPROVED** [review]
:+1:

**Comment by xuanxu** [comment]
@vchuravy I've just released a new version of the gem (1.5.2) that includes the updated config.

**Comment by vchuravy** [comment]
Thanks!

**Comment by vchuravy** [comment]
Do we also need to update the docker container so that https://github.com/JuliaCon/juliacon-proceedings-papers-testing/ can pick it up?

**Comment by xuanxu** [comment]
No need. The workflows should use the latest version now.

**Pull request merged**
